plugin: aws_ec2
regions:
  - us-east-1
  - ap-south-1
  - eu-west-1

keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
  - key: instance_type
    prefix: instance_type_

compose:
  ansible_host: public_ip_address

filters:
  instance-state-name: running
  tag:MonitorDisk: "True"
